# Generated by Django 3.1.2 on 2020-10-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201011_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
